name: compile xfrpc in ubuntu-latest 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    
    - name: prepare build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y libjson-c-dev libevent-dev libssl-dev

    - name: compile xfrpc
      run: |
        mkdir build
        cd build
        cmake ..
        make
