name: compile xfrpc in ubuntu-latest 

on:
  # Only manual trigger from Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v2
    
    - name: prepare build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y libjson-c-dev libevent-dev libssl-dev gcc-14 g++-14

    - name: compile xfrpc
      env:
        CC: gcc-14
        CXX: g++-14
      run: |
        mkdir build
        cd build
        cmake ..
        make
